import type { CommandCodeEffort } from './commandCodeThinking.js'

export interface CommandCodeCatalogModel {
  readonly id: string
  readonly name: string
  readonly contextWindow: number
  readonly inputTokens: number
  readonly outputTokens: number
  readonly promptCacheReadTokens: number
  readonly promptCacheWriteTokens: number
  readonly webSearchRequests: number
  readonly efforts: readonly CommandCodeEffort[]
}

export const COMMAND_CODE_85_MODELS: readonly CommandCodeCatalogModel[] = [
  {
    id: 'claude-fable-5',
    name: 'Claude Fable 5',
    contextWindow: 1000000,
    inputTokens: 10.0,
    outputTokens: 50.0,
    promptCacheReadTokens: 1.0,
    promptCacheWriteTokens: 12.5,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high', 'max'],
  },
  {
    id: 'claude-fable-5-1',
    name: 'Claude Fable 5.1',
    contextWindow: 1000000,
    inputTokens: 10.0,
    outputTokens: 50.0,
    promptCacheReadTokens: 0.25,
    promptCacheWriteTokens: 12.5,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high', 'max'],
  },
  {
    id: 'claude-haiku-4-5',
    name: 'Claude Haiku 4.5',
    contextWindow: 200000,
    inputTokens: 1.0,
    outputTokens: 5.0,
    promptCacheReadTokens: 0.1,
    promptCacheWriteTokens: 1.25,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'claude-opus-4-7',
    name: 'Claude Opus 4.7',
    contextWindow: 1000000,
    inputTokens: 5.0,
    outputTokens: 25.0,
    promptCacheReadTokens: 0.5,
    promptCacheWriteTokens: 6.25,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high', 'max'],
  },
  {
    id: 'claude-opus-4-8',
    name: 'Claude Opus 4.8',
    contextWindow: 1000000,
    inputTokens: 5.0,
    outputTokens: 25.0,
    promptCacheReadTokens: 0.5,
    promptCacheWriteTokens: 6.25,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high', 'max'],
  },
  {
    id: 'claude-opus-5',
    name: 'Claude Opus 5',
    contextWindow: 1000000,
    inputTokens: 5.0,
    outputTokens: 25.0,
    promptCacheReadTokens: 0.5,
    promptCacheWriteTokens: 6.25,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high', 'max'],
  },
  {
    id: 'claude-opus-5-5',
    name: 'Claude Opus 5.5',
    contextWindow: 1000000,
    inputTokens: 4.0,
    outputTokens: 20.0,
    promptCacheReadTokens: 0.2,
    promptCacheWriteTokens: 5.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high', 'max'],
  },
  {
    id: 'claude-sonnet-4-6',
    name: 'Claude Sonnet 4.6',
    contextWindow: 1000000,
    inputTokens: 3.0,
    outputTokens: 15.0,
    promptCacheReadTokens: 0.3,
    promptCacheWriteTokens: 3.75,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high', 'max'],
  },
  {
    id: 'claude-sonnet-5',
    name: 'Claude Sonnet 5',
    contextWindow: 1000000,
    inputTokens: 2.0,
    outputTokens: 10.0,
    promptCacheReadTokens: 0.2,
    promptCacheWriteTokens: 2.5,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high', 'max'],
  },
  {
    id: 'claude-sonnet-5-5',
    name: 'Claude Sonnet 5.5',
    contextWindow: 1000000,
    inputTokens: 2.0,
    outputTokens: 10.0,
    promptCacheReadTokens: 0.2,
    promptCacheWriteTokens: 2.5,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high', 'max'],
  },
  {
    id: 'deepseek-v-4-1-flash',
    name: 'DeepSeek V4.1 Flash',
    contextWindow: 1000000,
    inputTokens: 0.15,
    outputTokens: 0.6,
    promptCacheReadTokens: 0.003,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'deepseek-v-4-1-flash-fast',
    name: 'DeepSeek V4.1 Flash Fast',
    contextWindow: 1000000,
    inputTokens: 0.16,
    outputTokens: 0.58,
    promptCacheReadTokens: 0.016,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'deepseek-v-4-flash',
    name: 'DeepSeek V4 Flash (latest)',
    contextWindow: 1000000,
    inputTokens: 0.15,
    outputTokens: 0.6,
    promptCacheReadTokens: 0.003,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'deepseek-v-4-flash-fast',
    name: 'DeepSeek V4 Flash Fast',
    contextWindow: 1000000,
    inputTokens: 0.28,
    outputTokens: 0.56,
    promptCacheReadTokens: 0.07,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'deepseek-v-4-flash-vision',
    name: 'DeepSeek V4 Flash Vision (exp)',
    contextWindow: 1000000,
    inputTokens: 0.15,
    outputTokens: 0.6,
    promptCacheReadTokens: 0.003,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'deepseek-v-4-pro',
    name: 'DeepSeek V4 Pro (latest)',
    contextWindow: 1000000,
    inputTokens: 0.66,
    outputTokens: 1.98,
    promptCacheReadTokens: 0.022,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'low', 'medium', 'high'],
  },
  {
    id: 'fugu-ultra',
    name: 'Fugu Ultra',
    contextWindow: 1000000,
    inputTokens: 5.0,
    outputTokens: 30.0,
    promptCacheReadTokens: 0.5,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'gemini-3-1-flash-lite',
    name: 'Gemini 3.1 Flash Lite',
    contextWindow: 1000000,
    inputTokens: 0.25,
    outputTokens: 1.5,
    promptCacheReadTokens: 0.03,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium'],
  },
  {
    id: 'gemini-3-5-flash',
    name: 'Gemini 3.5 Flash',
    contextWindow: 1000000,
    inputTokens: 1.5,
    outputTokens: 9.0,
    promptCacheReadTokens: 0.15,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'gemini-3-5-flash-lite',
    name: 'Gemini 3.5 Flash Lite',
    contextWindow: 1000000,
    inputTokens: 0.3,
    outputTokens: 2.5,
    promptCacheReadTokens: 0.03,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium'],
  },
  {
    id: 'gemini-3-6-flash',
    name: 'Gemini 3.6 Flash',
    contextWindow: 1000000,
    inputTokens: 1.5,
    outputTokens: 7.5,
    promptCacheReadTokens: 0.15,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'gemini-3-7-flash',
    name: 'Gemini 3.7 Flash',
    contextWindow: 1000000,
    inputTokens: 1.5,
    outputTokens: 7.5,
    promptCacheReadTokens: 0.15,
    promptCacheWriteTokens: 0.08334,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'gemini-3-8-flash',
    name: 'Gemini 3.8 Flash',
    contextWindow: 1000000,
    inputTokens: 1.5,
    outputTokens: 7.5,
    promptCacheReadTokens: 0.15,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'glm-5',
    name: 'GLM-5',
    contextWindow: 200000,
    inputTokens: 1.0,
    outputTokens: 3.2,
    promptCacheReadTokens: 0.2,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'glm-5-1',
    name: 'GLM-5.1',
    contextWindow: 200000,
    inputTokens: 1.4,
    outputTokens: 4.4,
    promptCacheReadTokens: 0.26,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'glm-5-2',
    name: 'GLM-5.2',
    contextWindow: 1000000,
    inputTokens: 1.4,
    outputTokens: 4.4,
    promptCacheReadTokens: 0.26,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'glm-5-2-fast',
    name: 'GLM-5.2 Fast',
    contextWindow: 1000000,
    inputTokens: 3.0,
    outputTokens: 10.25,
    promptCacheReadTokens: 0.5,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'glm-5-3',
    name: 'GLM-5.3',
    contextWindow: 1000000,
    inputTokens: 1.4,
    outputTokens: 4.4,
    promptCacheReadTokens: 0.26,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'glm-5-3-flash',
    name: 'GLM-5.3 Flash',
    contextWindow: 1000000,
    inputTokens: 0.15,
    outputTokens: 0.5,
    promptCacheReadTokens: 0.03,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'glm-5-3-flashx',
    name: 'GLM-5.3 FlashX',
    contextWindow: 1000000,
    inputTokens: 0.37,
    outputTokens: 1.25,
    promptCacheReadTokens: 0.075,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'gpt-5-3-codex',
    name: 'GPT-5.3 Codex',
    contextWindow: 400000,
    inputTokens: 2.0,
    outputTokens: 8.0,
    promptCacheReadTokens: 0.5,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'minimal', 'low', 'medium', 'high'],
  },
  {
    id: 'gpt-5-4',
    name: 'GPT-5.4',
    contextWindow: 400000,
    inputTokens: 2.5,
    outputTokens: 15.0,
    promptCacheReadTokens: 0.25,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'minimal', 'low', 'medium', 'high'],
  },
  {
    id: 'gpt-5-4-mini',
    name: 'GPT-5.4 Mini',
    contextWindow: 400000,
    inputTokens: 0.75,
    outputTokens: 4.5,
    promptCacheReadTokens: 0.075,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'minimal', 'low', 'medium', 'high'],
  },
  {
    id: 'gpt-5-5',
    name: 'GPT-5.5',
    contextWindow: 400000,
    inputTokens: 5.0,
    outputTokens: 30.0,
    promptCacheReadTokens: 0.5,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'minimal', 'low', 'medium', 'high', 'max'],
  },
  {
    id: 'gpt-5-6-luna',
    name: 'GPT-5.6 Luna',
    contextWindow: 1100000,
    inputTokens: 0.2,
    outputTokens: 1.2,
    promptCacheReadTokens: 0.02,
    promptCacheWriteTokens: 0.25,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'minimal', 'low', 'medium', 'high'],
  },
  {
    id: 'gpt-5-6-sol',
    name: 'GPT-5.6 Sol',
    contextWindow: 1100000,
    inputTokens: 5.0,
    outputTokens: 30.0,
    promptCacheReadTokens: 0.5,
    promptCacheWriteTokens: 6.25,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'minimal', 'low', 'medium', 'high', 'max'],
  },
  {
    id: 'gpt-5-6-terra',
    name: 'GPT-5.6 Terra',
    contextWindow: 1100000,
    inputTokens: 2.0,
    outputTokens: 12.0,
    promptCacheReadTokens: 0.2,
    promptCacheWriteTokens: 2.5,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'minimal', 'low', 'medium', 'high', 'max'],
  },
  {
    id: 'gpt-6-1-sol',
    name: 'GPT-6.1 Sol',
    contextWindow: 1100000,
    inputTokens: 2.0,
    outputTokens: 10.0,
    promptCacheReadTokens: 0.1,
    promptCacheWriteTokens: 2.5,
    webSearchRequests: 0.01,
    efforts: ['default', 'low', 'medium', 'high', 'max'],
  },
  {
    id: 'gpt-6-astra',
    name: 'GPT-6 Astra',
    contextWindow: 1100000,
    inputTokens: 10.0,
    outputTokens: 50.0,
    promptCacheReadTokens: 1.0,
    promptCacheWriteTokens: 12.5,
    webSearchRequests: 0.01,
    efforts: ['default', 'low', 'medium', 'high', 'max'],
  },
  {
    id: 'gpt-6-luna',
    name: 'GPT-6 Luna',
    contextWindow: 1100000,
    inputTokens: 0.1,
    outputTokens: 0.5,
    promptCacheReadTokens: 0.01,
    promptCacheWriteTokens: 0.125,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'minimal', 'low', 'medium', 'high'],
  },
  {
    id: 'gpt-6-sol',
    name: 'GPT-6 Sol',
    contextWindow: 1100000,
    inputTokens: 2.0,
    outputTokens: 10.0,
    promptCacheReadTokens: 0.2,
    promptCacheWriteTokens: 2.5,
    webSearchRequests: 0.01,
    efforts: ['default', 'low', 'medium', 'high', 'max'],
  },
  {
    id: 'grok-4-5',
    name: 'Grok 4.5',
    contextWindow: 500000,
    inputTokens: 2.0,
    outputTokens: 6.0,
    promptCacheReadTokens: 0.5,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'high'],
  },
  {
    id: 'grok-4-6',
    name: 'Grok 4.6',
    contextWindow: 500000,
    inputTokens: 2.0,
    outputTokens: 6.0,
    promptCacheReadTokens: 0.5,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'high'],
  },
  {
    id: 'grok-4-7',
    name: 'Grok 4.7',
    contextWindow: 500000,
    inputTokens: 2.0,
    outputTokens: 6.0,
    promptCacheReadTokens: 0.5,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'high'],
  },
  {
    id: 'inkling',
    name: 'Inkling',
    contextWindow: 256000,
    inputTokens: 1.0,
    outputTokens: 4.05,
    promptCacheReadTokens: 0.17,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium'],
  },
  {
    id: 'inkling-small',
    name: 'Inkling Small',
    contextWindow: 1000000,
    inputTokens: 0.5,
    outputTokens: 1.2,
    promptCacheReadTokens: 0.1,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium'],
  },
  {
    id: 'jev',
    name: 'Jev',
    contextWindow: 32000,
    inputTokens: 0.042,
    outputTokens: 0.0,
    promptCacheReadTokens: 0.0,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default'],
  },
  {
    id: 'kimi-k-2-5',
    name: 'Kimi K2.5',
    contextWindow: 256000,
    inputTokens: 0.6,
    outputTokens: 3.0,
    promptCacheReadTokens: 0.1,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'kimi-k-2-6',
    name: 'Kimi K2.6',
    contextWindow: 256000,
    inputTokens: 0.95,
    outputTokens: 4.0,
    promptCacheReadTokens: 0.16,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'kimi-k-2-7-code',
    name: 'Kimi K2.7 Code',
    contextWindow: 256000,
    inputTokens: 0.95,
    outputTokens: 4.0,
    promptCacheReadTokens: 0.19,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'kimi-k-2-7-code-highspeed',
    name: 'Kimi K2.7 Code HighSpeed',
    contextWindow: 262000,
    inputTokens: 1.9,
    outputTokens: 8.0,
    promptCacheReadTokens: 0.38,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'kimi-k-3',
    name: 'Kimi K3',
    contextWindow: 1000000,
    inputTokens: 3.0,
    outputTokens: 15.0,
    promptCacheReadTokens: 0.3,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'low', 'high', 'max'],
  },
  {
    id: 'laguna-s-2-1',
    name: 'Laguna S 2.1',
    contextWindow: 256000,
    inputTokens: 0.0,
    outputTokens: 0.0,
    promptCacheReadTokens: 0.0,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default'],
  },
  {
    id: 'ling-3-0-flash-sante',
    name: 'Ling 3.0 Flash Sante',
    contextWindow: 262000,
    inputTokens: 0.0,
    outputTokens: 0.0,
    promptCacheReadTokens: 0.0,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default'],
  },
  {
    id: 'ling-3-1-flash',
    name: 'Ling 3.1 Flash',
    contextWindow: 262000,
    inputTokens: 0.0,
    outputTokens: 0.0,
    promptCacheReadTokens: 0.0,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default'],
  },
  {
    id: 'longcat-2-0',
    name: 'LongCat 2.0',
    contextWindow: 1000000,
    inputTokens: 0.3,
    outputTokens: 1.2,
    promptCacheReadTokens: 0.006,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'mimo-v-2-5',
    name: 'MiMo V2.5',
    contextWindow: 1000000,
    inputTokens: 0.14,
    outputTokens: 0.28,
    promptCacheReadTokens: 0.0028,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'mimo-v-2-5-pro',
    name: 'MiMo V2.5 Pro',
    contextWindow: 1000000,
    inputTokens: 0.435,
    outputTokens: 0.87,
    promptCacheReadTokens: 0.0036,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'mimo-v-2-6-flash',
    name: 'MiMo V2.6 Flash',
    contextWindow: 1000000,
    inputTokens: 0.14,
    outputTokens: 0.28,
    promptCacheReadTokens: 0.0028,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'mimo-v-2-6-pro',
    name: 'MiMo V2.6 Pro',
    contextWindow: 1000000,
    inputTokens: 0.435,
    outputTokens: 0.87,
    promptCacheReadTokens: 0.0036,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'mimo-v-2-6-pro-ultraspeed',
    name: 'MiMo V2.6 Pro UltraSpeed',
    contextWindow: 1000000,
    inputTokens: 4.35,
    outputTokens: 8.7,
    promptCacheReadTokens: 0.036,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'minimax-m-2-5',
    name: 'MiniMax M2.5',
    contextWindow: 200000,
    inputTokens: 0.3,
    outputTokens: 1.2,
    promptCacheReadTokens: 0.03,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'minimax-m-2-7',
    name: 'MiniMax M2.7',
    contextWindow: 200000,
    inputTokens: 0.3,
    outputTokens: 1.2,
    promptCacheReadTokens: 0.06,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'minimax-m-3',
    name: 'MiniMax M3',
    contextWindow: 1000000,
    inputTokens: 0.3,
    outputTokens: 1.2,
    promptCacheReadTokens: 0.06,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'muse-spark-1-1',
    name: 'Muse Spark 1.1',
    contextWindow: 1000000,
    inputTokens: 1.25,
    outputTokens: 4.25,
    promptCacheReadTokens: 0.15,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'muse-spark-1-2',
    name: 'Muse Spark 1.2',
    contextWindow: 1000000,
    inputTokens: 1.25,
    outputTokens: 4.25,
    promptCacheReadTokens: 0.15,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'muse-spark-1-2-contributor',
    name: 'Muse Spark 1.2 Contributor',
    contextWindow: 1000000,
    inputTokens: 0.1,
    outputTokens: 0.2,
    promptCacheReadTokens: 0.002,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'muse-spark-1-3',
    name: 'Muse Spark 1.3',
    contextWindow: 1000000,
    inputTokens: 1.25,
    outputTokens: 4.25,
    promptCacheReadTokens: 0.15,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'muse-spark-1-3-contributor',
    name: 'Muse Spark 1.3 Contributor',
    contextWindow: 1000000,
    inputTokens: 0.1,
    outputTokens: 0.2,
    promptCacheReadTokens: 0.002,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'nemotron-3-ultra',
    name: 'Nemotron 3 Ultra',
    contextWindow: 1000000,
    inputTokens: 0.6,
    outputTokens: 2.4,
    promptCacheReadTokens: 0.12,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'qwen-3-6-max-preview',
    name: 'Qwen 3.6 Max Preview',
    contextWindow: 200000,
    inputTokens: 1.3,
    outputTokens: 7.8,
    promptCacheReadTokens: 0.26,
    promptCacheWriteTokens: 1.63,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high', 'max'],
  },
  {
    id: 'qwen-3-6-plus',
    name: 'Qwen 3.6 Plus',
    contextWindow: 200000,
    inputTokens: 0.5,
    outputTokens: 3.0,
    promptCacheReadTokens: 0.1,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'qwen-3-7-flash',
    name: 'Qwen 3.7 Flash',
    contextWindow: 1000000,
    inputTokens: 0.03,
    outputTokens: 0.13,
    promptCacheReadTokens: 0.006,
    promptCacheWriteTokens: 0.038,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high', 'max'],
  },
  {
    id: 'qwen-3-7-max',
    name: 'Qwen 3.7 Max',
    contextWindow: 1000000,
    inputTokens: 2.5,
    outputTokens: 7.5,
    promptCacheReadTokens: 0.5,
    promptCacheWriteTokens: 3.13,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high', 'max'],
  },
  {
    id: 'qwen-3-7-plus',
    name: 'Qwen 3.7 Plus',
    contextWindow: 1000000,
    inputTokens: 0.4,
    outputTokens: 1.6,
    promptCacheReadTokens: 0.08,
    promptCacheWriteTokens: 0.5,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'qwen-3-8-27b',
    name: 'Qwen 3.8 27B',
    contextWindow: 262000,
    inputTokens: 0.4,
    outputTokens: 3.0,
    promptCacheReadTokens: 0.04,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'qwen-3-8-flash',
    name: 'Qwen 3.8 Flash',
    contextWindow: 1000000,
    inputTokens: 0.16,
    outputTokens: 0.47,
    promptCacheReadTokens: 0.016,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'qwen-3-8-max',
    name: 'Qwen 3.8 Max',
    contextWindow: 1000000,
    inputTokens: 2.0,
    outputTokens: 6.0,
    promptCacheReadTokens: 0.25,
    promptCacheWriteTokens: 2.5,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high', 'max'],
  },
  {
    id: 'qwen-3-8-max-0902',
    name: 'Qwen 3.8 Max 0902',
    contextWindow: 1000000,
    inputTokens: 2.0,
    outputTokens: 6.0,
    promptCacheReadTokens: 0.25,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high', 'max'],
  },
  {
    id: 'qwen-3-8-omni-flash',
    name: 'Qwen 3.8 Omni Flash',
    contextWindow: 1000000,
    inputTokens: 0.15,
    outputTokens: 0.47,
    promptCacheReadTokens: 0.016,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high', 'max'],
  },
  {
    id: 'step-3-5-flash',
    name: 'Step 3.5 Flash',
    contextWindow: 262000,
    inputTokens: 0.09,
    outputTokens: 0.3,
    promptCacheReadTokens: 0.02,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'low', 'medium', 'high'],
  },
  {
    id: 'step-3-7-flash',
    name: 'Step 3.7 Flash',
    contextWindow: 256000,
    inputTokens: 0.2,
    outputTokens: 1.15,
    promptCacheReadTokens: 0.04,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'low', 'medium', 'high'],
  },
  {
    id: 'step-5-preview',
    name: 'Step 5 Preview',
    contextWindow: 1000000,
    inputTokens: 1.0,
    outputTokens: 2.7,
    promptCacheReadTokens: 0.05,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },
  {
    id: 'tencent-hy-3',
    name: 'Tencent Hy3',
    contextWindow: 262000,
    inputTokens: 0.14,
    outputTokens: 0.58,
    promptCacheReadTokens: 0.035,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium'],
  },
  {
    id: 'tencent-hy-4-preview',
    name: 'Tencent Hy4 Preview',
    contextWindow: 1000000,
    inputTokens: 0.834,
    outputTokens: 2.501,
    promptCacheReadTokens: 0.042,
    promptCacheWriteTokens: 0.0,
    webSearchRequests: 0.01,
    efforts: ['default', 'none', 'low', 'medium', 'high'],
  },

]

export function normalizeCommandCodeKey(raw: string): string {
  let leaf = (raw.split('/').pop() ?? raw).toLowerCase()
  leaf = leaf.replace(/\(.*?\)/g, '')
  leaf = leaf.replace(/([a-z]+)(\d+)/g, '$1-$2')
  leaf = leaf.replace(/[._\s]+/g, '-')
  leaf = leaf.replace(/[^a-z0-9-]/g, '')
  leaf = leaf.replace(/--+/g, '-')
  return leaf.replace(/^-+|-+$/g, '')
}

const CATALOG_BY_KEY = new Map<string, CommandCodeCatalogModel>()

for (const model of COMMAND_CODE_85_MODELS) {
  CATALOG_BY_KEY.set(model.id, model)
  const normName = normalizeCommandCodeKey(model.name)
  if (!CATALOG_BY_KEY.has(normName)) {
    CATALOG_BY_KEY.set(normName, model)
  }
}

export function findCommandCodeCatalogModel(
  modelId: string,
): CommandCodeCatalogModel | undefined {
  const key = normalizeCommandCodeKey(modelId)
  const exact = CATALOG_BY_KEY.get(key)
  if (exact) return exact

  // Substring fallback for version/alias variants
  for (const [k, entry] of CATALOG_BY_KEY.entries()) {
    if (key.includes(k) || k.includes(key)) {
      return entry
    }
  }

  return undefined
}

export function getCommandCodeCatalogContextWindow(
  modelId: string,
): number | undefined {
  return findCommandCodeCatalogModel(modelId)?.contextWindow
}

export function getCommandCodeCatalogCosts(
  modelId: string,
): {
  inputTokens: number
  outputTokens: number
  promptCacheReadTokens: number
  promptCacheWriteTokens: number
  webSearchRequests: number
} | null {
  const model = findCommandCodeCatalogModel(modelId)
  if (!model) return null
  return {
    inputTokens: model.inputTokens,
    outputTokens: model.outputTokens,
    promptCacheReadTokens: model.promptCacheReadTokens,
    promptCacheWriteTokens: model.promptCacheWriteTokens,
    webSearchRequests: model.webSearchRequests,
  }
}

export function getCommandCodeCatalogEfforts(
  modelId: string,
): readonly CommandCodeEffort[] | undefined {
  return findCommandCodeCatalogModel(modelId)?.efforts
}

export function getCommandCodeCatalogDisplayName(
  modelId: string,
): string | undefined {
  return findCommandCodeCatalogModel(modelId)?.name
}
